# Taskfile for devenv containers project
# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build the container using the devcontainer cli
    cmds:
      - devcontainer build --workspace-folder src
